openapi: 3.0.1
info:
  title: Documentación de API de Productos
  description: Documentación de la API para la gestión de productos.
  version: 1.0.0

paths:
  /products:
    get:
      tags:          
        - Products   
      summary: Obtener lista de productos de mongo DB y renderizarlos
      description: Retorna una lista de productos paginados y ordenados opcionalmente.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Cantidad máxima de productos por página.
        - in: query
          name: page
          schema:
            type: integer
          description: Número de página .
        - in: query
          name: sort
          schema:
            type: string
          description: Orden de los productos (asc para ascendente, desc para descendente) (opcional).
        - in: query
          name: query
          schema:
            type: string
          description: Búsqueda de productos por título (opcional).
      responses:
        '200':
          description: Respuesta exitosa. Retorna la lista de productos paginados.
          content:
            application/json:
              example:
                status: success
                payload:
                  - _id: "605db372e9e8f7c6c49d4587"
                    title: Producto 1
                    price: 10
                  - _id: "605db374e9e8f7c6c49d4588"
                    title: Producto 2
                    price: 20
                totalPages: 2
                prevPage: 1
                nextPage: 2
                page: 1
                hasPrevPage: false
                hasNextPage: true
                prevLink: null
                nextLink: "http://localhost:4000/products?limit=2&page=2"
        '500':
          description: Error interno del servidor. No se pudieron obtener los productos.
